# Generated by Django 4.1.1 on 2022-11-17 17:53

import django.core.validators
from django.db import migrations, models
import petstagram.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Soy MinLengthValidator -> El nombre debe ser al menos 2'), petstagram.accounts.models.only_alpha_validadtor]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[petstagram.accounts.models.custom_min_length_validator, petstagram.accounts.models.only_alpha_validadtor]),
        ),
    ]
