# Generated by Django 4.1.1 on 2022-11-19 12:10

import django.core.validators
from django.db import migrations, models
import petstagram.photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pets_photos', validators=[petstagram.photos.models.file_size_5mb_validator, django.core.validators.validate_image_file_extension])),
                ('descrtiption', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
                ('location', models.CharField(max_length=30)),
                ('tagged_pets', models.ManyToManyField(null=True, to='pets.pet')),
            ],
        ),
    ]
