# Generated by Django 4.1.1 on 2022-11-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='tagged_pets',
            field=models.ManyToManyField(to='pets.pet'),
        ),
    ]
