# Generated by Django 4.1.1 on 2022-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_photos_tagged_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
