# Generated by Django 4.1.1 on 2022-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pet_photo', models.URLField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
    ]
